### ISSUE TITLE
Preview Java compilation tests started failing

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#257]
Refer to the checks failing here: https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/256 
[AB#9313](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9313)

**Comment by zengin** [comment]
@baywet can you please have a look at this issue when you get a chance?

**Comment by baywet** [comment]
@zengin the issue was fixed by this commit, it seems the jacoco team pulled all the snapshots when the released the version.
https://github.com/microsoftgraph/msgraph-sdk-java-core/commit/29377df5560978365d0d97d35eedf6b2323c021a
You might still see the issue until I release core 2.0.2, which is scheduled to go out anytime soon now.

**Comment by zengin** [comment]
Thanks for the information. This is not urgent, so I am OK with continuing to select `master`.
