### ISSUE TITLE
Consider allowing test execution to continue when DevX returns HTTP 404 for Delegated and Application Permissions

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#690]
When DevX returns HTTP 404 for both Delegated Permissions and Application Permissions, consider allowing execution to continue since test may still pass in Application permissions when using `.default` permission. 

Example is external connections test where DevX returns null for both Delegated and Application Permission but the test passes with assumed `.default` permission. Especially since we disregard returned application permission, as stated in the code comment. 

https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/e24c3e1c2a3340078ad31bbf49d6e69af271e36d/msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs#L289-L301

**Comment by zengin** [comment]
Thank you @georgend for raising this. I will take the opportunity to document the behavior that was decided earlier.

As discussed in the meeting, this was a deliberate choice. We don't want to continue running the tests even if we know that the test will succeed with the application permissions.

We would like to have all the permission information captured in the DevX API and all the missing ones getting caught at the expense of increased failing test number.

Hopefully the new permission data infrastructure will get funded soon, because there seems to be a lot of interest in all of M365 for structured data capturing permissions. We will then be able to test whether those will be fixed when DevX API transitions to using the new data format.
